<?php

if (!module_load_include('php', 'consolidator', 'autoload')) {
  throw new \Exception('Could not find autoloader.');
}

use consolidator\App;
use consolidator\ReportType\ReportType;

/**
 * Batch operation information.
 */
function consolidator_batch_operation(ReportType $object, &$context) {
  return App::instance()->batchOperation($object, $context);
}

/**
 * Called when a batch operation is finished.
 */
function consolidator_batch_finished($success, $results, $operations) {
  return App::instance()->batchFinished($success, $results, $operations);
}

/**
 * Callback for the consolidator admin form.
 */
function consolidator_form() : array {
  return App::instance()->form();
}

/**
 * Submit handler for the consolidator admin form.
 */
function consolidator_form_submit($form, &$form_state) {
  return App::instance()->formSubmit($form, $form_state);
}

/**
 * Implements hook_menu().
 */
function consolidator_menu() : array {
  return App::instance()->hookMenu();
}

/**
 * Implements hook_permission().
 */
function consolidator_permission() : array {
  return App::instance()->hookPermission();
}
