<?php

if (!module_load_include('php', 'consolidator_example', 'autoload')) {
  throw new \Exception('Could not find autoloader.');
}

use consolidator_example\ReportType\CleanAirStarWarsReport;
use consolidator_example\ReportType\CleanAirStarWarsReportDisk;
use consolidator_example\ReportType\CurrentSpaceStationLocation;

function consolidator_example_consolidator_reports() {

  return [
    new CleanAirStarWarsReport(),
    new CleanAirStarWarsReportDisk(),
    new CurrentSpaceStationLocation(),
  ];

}
